In [1]:
import numpy as np
from numpy import matlib
from scipy import sparse 
#np.set_printoptions(threshold=np.inf) # print all entries
import mlext as me

### Exercise 2

In [11]:
k = 10
n = 7
V = np.random.randint(1, k, n)
print(V)

[1 3 6 8 2 7 2]


In [23]:
### a ###
def count_occurances(k, V):
    C = np.unique(V, return_counts=True)
    return me.accumarray(C[0]-1, C[1], sz=k, fillval=0).astype(int)

In [24]:
count_occurances(10, V)

array([1, 2, 1, 0, 0, 1, 1, 1, 0, 0])

In [55]:
### b ###
def first_occ_index(k, V):
    C = np.unique(V,return_index=True)
    return me.accumarray(C[0]-1, C[1]+1, sz=k, fillval=0).astype(int)

In [56]:
first_occ_index(k, V)

array([1, 5, 2, 0, 0, 3, 6, 4, 0, 0])

### Exercise 3

In [7]:
v = np.zeros(6, dtype=np.int32)
v[[0,2,4,2,0]] = v[[0,2,4,2,0]] + 1 
print(v)

[1 0 1 0 1 0]


[2,0,2,0,1,0] would also have been possible. As indices 0 and 2 occur twice in the indexing of $\vec{v}$

### Exercise 4

In [8]:
v = np.array([1,4,4,3,2,0,1.5,1,4,3])

In [81]:
### a ###
v[[3,6,8]] = [8,7,-7]

In [86]:
### b ###
v[3:6] = [8,7,-7]

In [88]:
### c ###
v[v==4] = -7

In [9]:
### d ###
np.logical_and(v < 4, v >= 2).astype(int)

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1])

In [10]:
### e ###
np.nonzero(np.logical_and(v < 4, v >= 2))[0]

array([3, 4, 9])

In [126]:
### f ###
np.count_nonzero(v == 4)

3

In [127]:
### g ###
np.delete(v, [2,5,7])

array([1. , 4. , 3. , 2. , 1.5, 4. , 3. ])

In [130]:
### h ###
v[np.nonzero(v)[0]]

array([1. , 4. , 4. , 3. , 2. , 1.5, 1. , 4. , 3. ])

In [131]:
### i ###
np.count_nonzero(v)

9

### Exercise 5

In [42]:
I = [8, 6, 3, 6, 8, 9]; J = [3, 8, 7]

In [48]:
### a ###

S = count_occurances(10, I)
T = count_occurances(10, J)

A = np.logical_and( (S > 0), (T == 0) )
np.nonzero(A)[0] + 1

In [86]:
### b ###


### Exercise 6

In [65]:
### a ###
v = np.random.randint(1,10,10**7)
np.argmin(v)

3

In [67]:
### b ###
np.where(v == np.min(v))[0]

array([      3,      21,      43, ..., 9999988, 9999989, 9999994])

In [68]:
### c ###
count_occurances(9, v)

array([1111417, 1110267, 1111253, 1110054, 1110814, 1111341, 1110380,
       1111631, 1112843])

### Exercise 7

In [19]:
n = 8
A = matlib.repmat(np.arange(1,n+1), 8,1)

In [20]:
print(A)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### Exercise 8

In [69]:
A = me.magic(8)

In [88]:
me.print_matrix(A)

AttributeError: 'NoneType' object has no attribute 'join'

In [87]:
A[sparse.find(A < 32)[:-1]] = 0
print(A)

[[64  0  0 61 60  0  0 57]
 [ 0 55 54  0  0 51 50  0]
 [ 0 47 46  0  0 43 42  0]
 [40  0  0 37 36  0  0 33]
 [32 34 35  0  0 38 39  0]
 [41  0  0 44 45  0  0 48]
 [49  0  0 52 53  0  0 56]
 [ 0 58 59  0  0 62 63  0]]
