In [1]:
import sys
sys.path.append('./given_material/')
import numpy as np
from numpy import matlib
from scipy import sparse 
#np.set_printoptions(threshold=np.inf) # print all entries
import mlext as me

### Exercise 2

In [11]:
k = 10
n = 7
V = np.random.randint(1, k, n)
print(V)

[1 3 6 8 2 7 2]


In [23]:
### a ###
def count_occurances(k, V):
    C = np.unique(V, return_counts=True)
    return me.accumarray(C[0]-1, C[1], sz=k, fillval=0).astype(int)

In [24]:
count_occurances(10, V)

array([1, 2, 1, 0, 0, 1, 1, 1, 0, 0])

In [55]:
### b ###
def first_occ_index(k, V):
    C = np.unique(V,return_index=True)
    return me.accumarray(C[0]-1, C[1]+1, sz=k, fillval=0).astype(int)

In [56]:
first_occ_index(k, V)

array([1, 5, 2, 0, 0, 3, 6, 4, 0, 0])

### Exercise 3

In [7]:
v = np.zeros(6, dtype=np.int32)
v[[0,2,4,2,0]] = v[[0,2,4,2,0]] + 1 
print(v)

[1 0 1 0 1 0]


[2,0,2,0,1,0] would also have been possible. As indices 0 and 2 occur twice in the indexing of $\vec{v}$

### Exercise 4

In [8]:
v = np.array([1,4,4,3,2,0,1.5,1,4,3])

In [81]:
### a ###
v[[3,6,8]] = [8,7,-7]

In [86]:
### b ###
v[3:6] = [8,7,-7]

In [88]:
### c ###
v[v==4] = -7

In [9]:
### d ###
np.logical_and(v < 4, v >= 2).astype(int)

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1])

In [10]:
### e ###
np.nonzero(np.logical_and(v < 4, v >= 2))[0]

array([3, 4, 9])

In [126]:
### f ###
np.count_nonzero(v == 4)

3

In [127]:
### g ###
np.delete(v, [2,5,7])

array([1. , 4. , 3. , 2. , 1.5, 4. , 3. ])

In [130]:
### h ###
v[np.nonzero(v)[0]]

array([1. , 4. , 4. , 3. , 2. , 1.5, 1. , 4. , 3. ])

In [131]:
### i ###
np.count_nonzero(v)

9

### Exercise 5

In [42]:
I = [8, 6, 3, 6, 8, 9]; J = [3, 8, 7]

In [48]:
### a ###

S = count_occurances(10, I)
T = count_occurances(10, J)

A = np.logical_and( (S > 0), (T == 0) )
np.nonzero(A)[0] + 1

In [86]:
### b ###


### Exercise 6

In [65]:
### a ###
v = np.random.randint(1,10,10**7)
np.argmin(v)

3

In [67]:
### b ###
np.where(v == np.min(v))[0]

array([      3,      21,      43, ..., 9999988, 9999989, 9999994])

In [68]:
### c ###
count_occurances(9, v)

array([1111417, 1110267, 1111253, 1110054, 1110814, 1111341, 1110380,
       1111631, 1112843])

### Exercise 7

In [19]:
n = 8
A = matlib.repmat(np.arange(1,n+1), 8,1)

In [20]:
print(A)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### Exercise 8

In [90]:
A = me.magic(8)

In [91]:
print(A)

[[64  2  3 61 60  6  7 57]
 [ 9 55 54 12 13 51 50 16]
 [17 47 46 20 21 43 42 24]
 [40 26 27 37 36 30 31 33]
 [32 34 35 29 28 38 39 25]
 [41 23 22 44 45 19 18 48]
 [49 15 14 52 53 11 10 56]
 [ 8 58 59  5  4 62 63  1]]


In [98]:
### a ###
def ex8a(mat):
    mat[sparse.find(mat < 32)[:-1]] = 0
    print(mat)

ex8a(A.copy())

[[64  0  0 61 60  0  0 57]
 [ 0 55 54  0  0 51 50  0]
 [ 0 47 46  0  0 43 42  0]
 [40  0  0 37 36  0  0 33]
 [32 34 35  0  0 38 39  0]
 [41  0  0 44 45  0  0 48]
 [49  0  0 52 53  0  0 56]
 [ 0 58 59  0  0 62 63  0]]


In [95]:
### b ###
print(np.delete(A.copy(), 5, axis=-1))

[[64  2  3 61 60  7 57]
 [ 9 55 54 12 13 50 16]
 [17 47 46 20 21 42 24]
 [40 26 27 37 36 31 33]
 [32 34 35 29 28 39 25]
 [41 23 22 44 45 18 48]
 [49 15 14 52 53 10 56]
 [ 8 58 59  5  4 63  1]]


In [99]:
### c ###
print(np.delete(A.copy(), -1, axis=0))

[[64  2  3 61 60  6  7 57]
 [ 9 55 54 12 13 51 50 16]
 [17 47 46 20 21 43 42 24]
 [40 26 27 37 36 30 31 33]
 [32 34 35 29 28 38 39 25]
 [41 23 22 44 45 19 18 48]
 [49 15 14 52 53 11 10 56]]


In [100]:
### d ###
def ex8d(mat, I, J):
    A[I,J] = 0
    return A

I = [3, 1, 3, 6]
J = [1, 2, 7, 4]

print(ex8d(A.copy(), I, J))

[[64  2  3 61 60  6  7 57]
 [ 9 55  0 12 13 51 50 16]
 [17 47 46 20 21 43 42 24]
 [40  0 27 37 36 30 31  0]
 [32 34 35 29 28 38 39 25]
 [41 23 22 44 45 19 18 48]
 [49 15 14 52  0 11 10 56]
 [ 8 58 59  5  4 62 63  1]]


In [101]:
### e ###
def ex8e(n):
    return np.diag(np.arange(1,n+1))

print(ex8e(5))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Exercise 9

In [105]:
np.random.seed(623827)
n = 8; d = 0.1
A = sparse.rand(n, n, d,format="csc"); 
print(A.todense())


[[0.         0.         0.         0.         0.37189458 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.71963797 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.02584222 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.50721234 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.9507732  0.         0.         0.79845092 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]


In [82]:
### a ###
def ex9a(matrix):
    I, J, V = sparse.find(matrix)
    matrix[I, J] = 10*I + J

    return matrix.todense()

ex9a(A.copy())

matrix([[ 0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [20.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [30.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 43.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0., 61.,  0.,  0., 64.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [83]:
### b ###
def ex9b(matrix):
    I, J, _ = sparse.find(matrix == 0)
    matrix[I, J] = 2

    return matrix.todense()

ex9b(A.copy())

/Users/larsschilders/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SparseEfficiencyWarning: Comparing a sparse matrix with 0 using == is inefficient, try using != instead.
  
/Users/larsschilders/opt/anaconda3/lib/python3.7/site-packages/scipy/sparse/_index.py:126: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


matrix([[2.        , 2.        , 2.        , 2.        , 0.37189458,
         2.        , 2.        , 2.        ],
        [2.        , 2.        , 2.        , 2.        , 2.        ,
         2.        , 2.        , 2.        ],
        [0.71963797, 2.        , 2.        , 2.        , 2.        ,
         2.        , 2.        , 2.        ],
        [0.02584222, 2.        , 2.        , 2.        , 2.        ,
         2.        , 2.        , 2.        ],
        [2.        , 2.        , 2.        , 0.50721234, 2.        ,
         2.        , 2.        , 2.        ],
        [2.        , 2.        , 2.        , 2.        , 2.        ,
         2.        , 2.        , 2.        ],
        [2.        , 0.9507732 , 2.        , 2.        , 0.79845092,
         2.        , 2.        , 2.        ],
        [2.        , 2.        , 2.        , 2.        , 2.        ,
         2.        , 2.        , 2.        ]])

In [84]:
### c ###
def ex9c(matrix):
    I, J, V = sparse.find(matrix)
    matrix[I, J] = J

    return matrix.todense()

ex9c(A.copy())

matrix([[0., 0., 0., 0., 4., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 3., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 4., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [107]:
### d ###
A.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.37189458,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.71963797, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.02584222, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.50721234, 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.9507732 , 0.        , 0.        , 0.79845092,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ]])

In [116]:
sparse.find(A)

(array([2, 3, 6, 4, 0, 6], dtype=int32),
 array([0, 0, 1, 3, 4, 4], dtype=int32),
 array([0.71963797, 0.02584222, 0.9507732 , 0.50721234, 0.37189458,
        0.79845092]))

### Exercise 10

In [214]:
n = 7
np.random.seed(10)
suit, rank = np.random.randint(1, 14, size=n), np.random.randint(1, 5, size=n)

H = np.array(list(zip(suit,rank, np.arange(n))))
print(np.delete(H,2,axis=1))

H_sorted_on_rank = H[np.argsort(H[:,0])[::-1]]
# print(H_sorted_on_rank)
H_highest_rank_per_suit = H_sorted_on_rank[np.unique(H_sorted_on_rank[:,1], return_index=True)[1]]
sorted_answer = H_highest_rank_per_suit[np.argsort(H_highest_rank_per_suit[:,2])]
np.delete(sorted_answer,2, axis=1)

[[10  2]
 [ 5  1]
 [ 1  2]
 [ 2  2]
 [12  3]
 [13  1]
 [10  2]]


array([[12,  3],
       [13,  1],
       [10,  2]])