## Required imports

In [1]:
import numpy as np
import numpy_indexed
import given_material.mlext as me
from scipy import sparse
import timeit
import functools

## General
Note, that in general, for every question where an index was asked, we added +1 to the result.
This is to prevent confusion between 0 (no result) and 0 (index).
This does result in some clunky notation, but in the nicest output possible.

Furthermore, we have adapted the print_matrix command in the given material to also include a header.
There was also a bug there we fixed.

# Exercise 2

In [2]:
# 2a
n=7; k=10; V = np.random.randint(low=1, high=k+1, size=n)  # declare inputs

count_occurrences = lambda _: np.bincount(_, minlength=k+1)[1:]
print(f"Input array:\t{V}")
print(f"Result 2a:\t{count_occurrences(V)}")

Input array:	[8 5 6 6 8 2 5]
Result 2a:	[0 1 0 0 2 2 0 2 0 0]


In [3]:
# 2b
def first_occurrence_index(v):
    v_unique, v_indices = np.unique(v, return_index=True)
    return np.bincount(v_unique, weights=v_indices+1, minlength=k)[1:].astype(np.int16)

print(f"Input array:\t{V}")
print(f"Result 2b:\t{first_occurrence_index(V)}")

Input array:	[8 5 6 6 8 2 5]
Result 2b:	[0 6 0 0 2 3 0 1 0]


# Exercise 3

In [4]:
v = np.zeros(6, dtype=np.int32)
v[[0,2,4,2,0]] = v[[0,2,4,2,0]] + 1 
print(f'Result given \t\t: {v}')
print(f'Possible solution \t: {np.asarray([2, 0, 1, 0, 2, 0])}')

Result given 		: [1 0 1 0 1 0]
Possible solution 	: [2 0 1 0 2 0]


As indices 0 and 2 occur twice, it would have been possible that these would get +1 twice.
However, this is not the case, resulting in [1 0 1 0 1 0], even though [2 0 1 0 2 0] could have been possible.

# Exercise 4

In [5]:
def ex4abc(array, indices, values):
    array[indices] = values
    return array

def ex4d(array, lb, ub):
    return np.logical_and(array >= lb, array < ub)

def ex4e(array, lb, ub):
    return np.logical_and(array >= lb, array < ub).nonzero()[0]

def ex4f(array, value):
    return len(array[array == value])

def ex4g(array, to_delete):
    return np.delete(array, to_delete)

def ex4h(array):
    return array[array.nonzero()]

def ex4i(array):
    return len(array[array.nonzero()])

v = np.asarray([1, 4, 4, 3, 2, 0, 1.5, 1, 4, 3])  # reset
print(f'Base array \t: {v}')
print(f'a) Result \t: {ex4abc(v.copy(), [2, 5, 7], [8, 7, -7])}')
print(f'b) Result \t: {ex4abc(v.copy(), slice(2,6), [8, 7, -7, 1])}')
print(f'c) Result \t: {ex4abc(v.copy(), v==4, -7)}')
print(f'd) Result \t: {ex4d(v.copy(), 2, 4)}')
print(f'e) Result \t: {ex4e(v.copy(), 2, 4)}')
print(f'f) Result \t: {ex4f(v.copy(), 4)}')
print(f'g) Result \t: {ex4g(v.copy(), [2, 5, 7])}')
print(f'h) Result \t: {ex4h(v.copy())}')
print(f'i) Result \t: {ex4i(v.copy())}')

Base array 	: [1.  4.  4.  3.  2.  0.  1.5 1.  4.  3. ]
a) Result 	: [ 1.   4.   8.   3.   2.   7.   1.5 -7.   4.   3. ]
b) Result 	: [ 1.   4.   8.   7.  -7.   1.   1.5  1.   4.   3. ]
c) Result 	: [ 1.  -7.  -7.   3.   2.   0.   1.5  1.  -7.   3. ]
d) Result 	: [False False False  True  True False False False False  True]
e) Result 	: [3 4 9]
f) Result 	: 3
g) Result 	: [1.  4.  3.  2.  1.5 4.  3. ]
h) Result 	: [1.  4.  4.  3.  2.  1.5 1.  4.  3. ]
i) Result 	: 9


# Exercise 5

In [6]:
def ex5a(large, small):
    maxlength = np.max(np.concatenate([large, small]))+1
    S = np.bincount(large, minlength = maxlength)
    T = np.bincount(small, minlength = maxlength)
    A = np.logical_and((S > 0), (T == 0))
    return np.nonzero(A)[0]


I = np.array([8, 6, 3, 6, 8, 9]); J = np.array([3, 8, 7])  # define inputs

print(f'Input array I:\t{I}')
print(f'Input array J:\t{J}')
print(f'Result:\t\t{ex5a(I, J)}')

Input array I:	[8 6 3 6 8 9]
Input array J:	[3 8 7]
Result:		[6 9]


In [7]:
# 5b
def ex5b(large, small):
    return large[~np.isin(large, small)]

print(f'Result 5b: {ex5b(I, J)}')

Result 5b: [6 6 9]


# Exercise 6

In [8]:
v = np.random.randint(1, 10, 10**7)  # declare input

print(f'Result 6a:\t{np.argmin(v)}')
print(f'Result 6b:\t{np.where(v == v.min())[0]}')
print(f'Result 6c:\t{np.bincount(v, minlength = 10)[1:]}')

Result 6a:	7
Result 6b:	[      7      15      28 ... 9999985 9999990 9999995]
Result 6c:	[1110125 1112408 1110418 1110587 1110467 1111113 1110845 1112738 1111299]


# Exercise 7

In [9]:
def ex7(n):
    return np.tile(np.arange(1, n+1), (n, 1))

n = 8  # declare size
me.print_matrix('Result 7', ex7(n))

Result 7
  1  2  3  4  5  6  7  8
  1  2  3  4  5  6  7  8
  1  2  3  4  5  6  7  8
  1  2  3  4  5  6  7  8
  1  2  3  4  5  6  7  8
  1  2  3  4  5  6  7  8
  1  2  3  4  5  6  7  8
  1  2  3  4  5  6  7  8


# Exercise 8

In [10]:
def ex8a(matrix, value):
    matrix[matrix < value] = 0
    return matrix

def ex8bc(matrix, n_col_row, n_axis):
    return np.delete(matrix, n_col_row, axis=n_axis)

def ex8d(matrix, values):
    matrix[values] = 0
    return matrix

def ex8e_1(size):
    return np.diag(np.arange(1, size+1, dtype=int))

def ex8e_3(size):
    # with some form of linear addressing
    matrix = np.zeros(size * size, dtype=np.int)
    matrix[np.array(range(0, size)) * size + np.array(range(0, size))] = range(1, size + 1)
    return np.reshape(matrix, (size, size))


size = 8  # input size
A = me.magic(size)
me.print_matrix('Base matrix:', A)
me.print_matrix('Result a)', ex8a(A.copy(), 32))
me.print_matrix('Result b)', ex8bc(A.copy(), 4, 0))
me.print_matrix('Result c)', ex8bc(A.copy(), -1, 1))
input_I = [3, 1, 3, 6]
input_J = [1, 2, 7, 4]
me.print_matrix('Result d)', ex8d(A.copy(), (input_I, input_J)))
me.print_matrix('Result e)', ex8e_1(size))
me.print_matrix('Result e)', ex8e_3(size))

Base matrix:
  64   2   3  61  60   6   7  57
   9  55  54  12  13  51  50  16
  17  47  46  20  21  43  42  24
  40  26  27  37  36  30  31  33
  32  34  35  29  28  38  39  25
  41  23  22  44  45  19  18  48
  49  15  14  52  53  11  10  56
   8  58  59   5   4  62  63   1
Result a)
  64   0   0  61  60   0   0  57
   0  55  54   0   0  51  50   0
   0  47  46   0   0  43  42   0
  40   0   0  37  36   0   0  33
  32  34  35   0   0  38  39   0
  41   0   0  44  45   0   0  48
  49   0   0  52  53   0   0  56
   0  58  59   0   0  62  63   0
Result b)
  64   2   3  61  60   6   7  57
   9  55  54  12  13  51  50  16
  17  47  46  20  21  43  42  24
  40  26  27  37  36  30  31  33
  41  23  22  44  45  19  18  48
  49  15  14  52  53  11  10  56
   8  58  59   5   4  62  63   1
Result c)
  64   2   3  61  60   6   7
   9  55  54  12  13  51  50
  17  47  46  20  21  43  42
  40  26  27  37  36  30  31
  32  34  35  29  28  38  39
  41  23  22  44  45  19  18
  49  15  14  52  53  11

In the exercise above, we offer two solutions to 8e.
It was asked to use linear index addressing, however, this does if not exist in numpy:
Therefore, we decided to work around this, by initially declaring the matrix as a vector.
This way, linear adressing can be used, even though it is likely not as efficient as the one-line solution offered.

# Exercise 9

In [11]:
# declare inputs
np.random.seed(623827)
n = 8; d = 0.1
A = sparse.rand(n, n, d, format='csc')
me.print_matrix('Base matrix A', A.todense())

def ex9a(matrix):
    I, J, V = sparse.find(matrix)
    matrix[I, J] = 10*I + J
    return matrix.todense().astype(np.int16)

def ex9b(matrix):
    matrix[matrix == 0] = 2
    return matrix.todense()

def ex9c(matrix):
    I, J, V = sparse.find(matrix)
    matrix[I, J] = J
    return matrix.todense().astype(np.int16)

def ex9d(matrix):
    idx_i, idx_j, val = sparse.find(matrix)
    concat_values = np.stack([idx_i, val], axis=1)
    argmax_indices = np.stack(numpy_indexed.group_by(keys=idx_j, values=concat_values, reduction=lambda x: x[x[:,1].argmax(),0]+1), axis=1).astype(int)
    return np.bincount(argmax_indices[0], weights=argmax_indices[1], minlength=matrix.shape[0])


me.print_matrix('Result 9a', ex9a(A.copy()))
me.print_matrix('Result 9b', ex9b(A.copy()))
me.print_matrix('Result 9c', ex9c(A.copy()))
A_d = np.asarray([[0, 1, 0, 2, 0, 9, -3, 8, 0, -9], [3, 0, 0, 0, 0, 0, 0, 0, 0, 4], [0, 7, 0, 8, 0, 0, 0, 0, 0, -4],
                  [-8, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, -1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, -2, 0, -9, 0, 0, 0],
                  [0, 0, 0, -3, 0, 0, -9, 0, 0, 0] ,[0, 0, -8, -2, 2, 0, 0, -8, 0, 0],
                  [0, 0, -8, 0, 0, 7, -8, -9, 0, 0], [-8, 0, 8, 0, 0, 0, -1, 0, 0, 0]])
print(f'Exercise 9d) {ex9d(A_d.copy())}')

Base matrix A
  [[0.         0.         0.         0.         0.37189458 0.
  0.         0.        ]]
                                                            [[0. 0. 0. 0. 0. 0. 0. 0.]]
  [[0.71963797 0.         0.         0.         0.         0.
  0.         0.        ]]
  [[0.02584222 0.         0.         0.         0.         0.
  0.         0.        ]]
  [[0.         0.         0.         0.50721234 0.         0.
  0.         0.        ]]
                                                            [[0. 0. 0. 0. 0. 0. 0. 0.]]
  [[0.         0.9507732  0.         0.         0.79845092 0.
  0.         0.        ]]
                                                            [[0. 0. 0. 0. 0. 0. 0. 0.]]
Result 9a
          [[0 0 0 0 4 0 0 0]]
          [[0 0 0 0 0 0 0 0]]
  [[20  0  0  0  0  0  0  0]]
  [[30  0  0  0  0  0  0  0]]
  [[ 0  0  0 43  0  0  0  0]]
          [[0 0 0 0 0 0 0 0]]
  [[ 0 61  0  0 64  0  0  0]]
          [[0 0 0 0 0 0 0 0]]
Result 9b
  [[2.         2.     

C:\Users\s150127\AppData\Local\Continuum\anaconda3\envs\ScientificProgramming\lib\site-packages\ipykernel_launcher.py:29: SparseEfficiencyWarning: Comparing a sparse matrix with 0 using == is inefficient, try using != instead.
C:\Users\s150127\AppData\Local\Continuum\anaconda3\envs\ScientificProgramming\lib\site-packages\scipy\sparse\_index.py:125: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


# Exercise 10

In [16]:
def ex10(H):
    ones = (H == (np.max(H[H[:, 1] == 1, 0], initial=0), 1)).all(axis=1)
    twos = (H == (np.max(H[H[:, 1] == 2, 0], initial=0), 2)).all(axis=1)
    threes = (H == (np.max(H[H[:, 1] == 3, 0], initial=0), 3)).all(axis=1)
    fours = (H == (np.max(H[H[:, 1] == 4, 0], initial=0), 4)).all(axis=1)
    return H[ones | twos | threes | fours]

## define random if you want
# n = 14
# ranks = np.random.randint(low=1, high=14, size=n)
# suites = np.random.randint(low=1, high=5, size=n)
# H = np.transpose(np.vstack((ranks, suites)))
# define example
H = np.array([[7, 1], [3, 2], [6, 1], [4, 2], [4, 2], [7, 1], [3, 4]])
print(f'Given array:\n{H}')
print("Result:")
print(ex10(H))

Given array:
[[7 1]
 [3 2]
 [6 1]
 [4 2]
 [4 2]
 [7 1]
 [3 4]]
Result:
[[7 1]
 [4 2]
 [4 2]
 [7 1]
 [3 4]]


# Exercise 11

In [13]:
# declare inputs
n=4; m=5
A = np.random.randint(-10, 10, size=(n,m))

# 11a
isL = lambda x: np.all(x.diagonal() > 0) & np.all(x[~np.eye(x.shape[0], x.shape[1], dtype=np.bool)] <=0)
me.print_matrix('Input Matrix:', A)
print(f'Is given matrix an L-matrix:\t {isL(A)}')

# 11b
A = sparse.csc_matrix([[1, 0, -2], [0, 4, 0], [-9, -2, 6]])  # new given matrix
me.print_matrix('Input Matrix:', A.todense())
print(f'Is given matrix an L-matrix:\t {isL(A)}')

# 11c
A = sparse.csc_matrix([[-2, -6, 0, 1], [5, 11, -8, -9], [0, 20, 22, -4], [3, 2, 1, -7]])   # new given matrix
me.print_matrix('Input Matrix:', A.todense())
print(f'Is given matrix an L-matrix:\t {isL(A)}')

Input Matrix:
   -7  -10   7   7   4
  -10   -8   3   0   6
   -9    0  -2   6  -1
    5   -9   4  -9   0
Is given matrix an L-matrix:	 False
Input Matrix:
  [[ 1  0 -2]]
     [[0 4 0]]
  [[-9 -2  6]]
Is given matrix an L-matrix:	 True
Input Matrix:
  [[-2 -6  0  1]]
  [[ 5 11 -8 -9]]
  [[ 0 20 22 -4]]
  [[ 3  2  1 -7]]
Is given matrix an L-matrix:	 False


# Exercise 12

In [14]:
# declare inputs
instances = 100
n = 10000

def f(n: int) -> np.array:
    A = np.zeros((n,n))
    for i in range(0,n):
        A[i,i] = 2
        if i > 1:
            A[i,i-1] = -1
        if i < n-1:
            A[i,i+1] = -1
    return A

def tridiag(n: int) -> np.array:
    return sparse.diags([-1, 2, -1], offsets=[-1, 0, 1], shape=(n,n))

# run function f
t = timeit.Timer(functools.partial(f, n))
f_time = t.timeit(instances) / instances
print(f"Timing for f: {f_time:.10f} s.")

# run function tridag
t = timeit.Timer(functools.partial(tridiag, n))
tridiag_time = t.timeit(instances) / instances
print(f"Timing for tridiag: {tridiag_time:.10f} s.")

# comparison
print(f"tridiag is {f_time / tridiag_time:.1f} times faster than f")

Timing for f: 0.0409370330 s.
Timing for tridiag: 0.0001977260 s.
tridiag is 207.0 times faster than f
