In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


TODO:

- 9d
- 10
- commenting

## Exercise 2

In [58]:
n=7; k=10; V=[3, 6, 9, 6, 4, 2, 8]

# code
count_occurances = lambda _: np.bincount(_, minlength=k+1)[1:]

# testing/timing
print(count_occurances(V))

[0 1 1 1 0 2 0 1 1 0]


In [59]:
n=7; k=10; V=[3, 6, 9, 6, 4, 2, 8]

# code
count_occurances = lambda _: np.bincount(_, minlength=k+1)[1:]

# testing/timing
print(count_occurances(V))

[0 1 1 1 0 2 0 1 1 0]


# Exercise 3

In [60]:
v = np.zeros(6, dtype=np.int32)
v[[0,2,4,2,0]] = v[[0,2,4,2,0]] + 1 
print(v)

[1 0 1 0 1 0]


# Exercise 4

In [6]:
def ex4abc(array, indices, values):
    array[indices] = values
    return array

def ex4d(array, lb, ub):
    return np.logical_and(array >= lb, array < ub)

def ex4e(array, lb, ub):
    return np.logical_and(array >= lb, array < ub).nonzero()[0]

def ex4f(array, value):
    return len(array[array == value])

def ex4g(array, to_delete):
    return np.delete(array, to_delete)

def ex4h(array):
    return array[array.nonzero()]

def ex4i(array):
    return len(array[array.nonzero()])

v = np.asarray([1, 4, 4, 3, 2, 0, 1.5, 1, 4, 3])  # reset
print(f'Base array \t: {v}')
print(f'a) Result \t: {ex4abc(v.copy(), [2, 5, 7], [8, 7, -7])}')
print(f'b) Result \t: {ex4abc(v.copy(), slice(2,6), [8, 7, -7, 1])}')
print(f'c) Result \t: {ex4abc(v.copy(), v==4, -7)}')
print(f'd) Result \t: {ex4d(v.copy(), 2, 4)}')
print(f'e) Result \t: {ex4e(v.copy(), 2, 4)}')
print(f'f) Result \t: {ex4f(v.copy(), 4)}')
print(f'g) Result \t: {ex4g(v.copy(), [2, 5, 7])}')
print(f'h) Result \t: {ex4h(v.copy())}')
print(f'i) Result \t: {ex4i(v.copy())}')

Base array 	: [1.  4.  4.  3.  2.  0.  1.5 1.  4.  3. ]
a) Result 	: [ 1.   4.   8.   3.   2.   7.   1.5 -7.   4.   3. ]
b) Result 	: [ 1.   4.   8.   7.  -7.   1.   1.5  1.   4.   3. ]
c) Result 	: [ 1.  -7.  -7.   3.   2.   0.   1.5  1.  -7.   3. ]
d) Result 	: [False False False  True  True False False False False  True]
e) Result 	: [3 4 9]
f) Result 	: 3
g) Result 	: [1.  4.  3.  2.  1.5 4.  3. ]
h) Result 	: [1.  4.  4.  3.  2.  1.5 1.  4.  3. ]
i) Result 	: 9


# Exercise 5

In [33]:
I = np.array([8, 6, 3, 6, 8, 9]); J = np.array([3, 8, 7])

## EXERCISE A
maxlength = np.max(np.concatenate([I,J]))+1
S = np.bincount(I, minlength = maxlength)
T = np.bincount(J, minlength = maxlength)
A = np.logical_and( (S > 0), (T == 0) )
print(np.nonzero(A)[0] )


## EXERCISE B
I[~np.isin(I, J)] 

[6 9]


array([6, 6, 9])

# Exercise 6

In [37]:
v = np.random.randint(1, 10, 10**7)

# Exercise 6a
print(np.argmin(v))

# Exercise 6b
print(np.where(v == v.min())[0])

# Exercise 6c
np.bincount(v, minlength = 10)[1:, np.newaxis]

0
[      0      15      20 ... 9999979 9999988 9999993]


array([[1109584],
       [1110628],
       [1111013],
       [1112369],
       [1112497],
       [1110548],
       [1112578],
       [1109819],
       [1110964]])

# Exercise 7

In [41]:
from numpy import matlib

n = 8
A = matlib.repmat(np.arange(1,n+1), n, 1)
A

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

# Exercise 8

In [47]:
import given_material.mlext as me


def ex8a(matrix, value):
    matrix[matrix < value] = 0
    return matrix

def ex8bc(matrix, n_col_row, n_axis):
    return np.delete(matrix, n_col_row, axis=n_axis)

def ex8d(matrix, values):
    matrix[values] = 0
    return matrix

def ex8e_1(size):
    return np.diag(np.arange(1, size+1, dtype=int))

def ex8e_3(size):
    # with some form of linear adressing
    matrix = np.zeros(size * size, dtype=np.int)
    matrix[np.array(range(0, size)) * size + np.array(range(0, size))] = range(1, size + 1)
    return np.reshape(matrix, (size, size))


size = 8
A = me.magic(size)
me.print_matrix('Base matrix:', A)
me.print_matrix('Result a)', ex8a(A.copy(), 32))
me.print_matrix('Result b)', ex8bc(A.copy(), 4, 0))
me.print_matrix('Result c)', ex8bc(A.copy(), -1, 1))
input_I = [3, 1, 3, 6]
input_J = [1, 2, 7, 4]
me.print_matrix('Result d)', ex8d(A.copy(), (input_I, input_J)))
me.print_matrix('Result e)', ex8e_1(size))
me.print_matrix('Result e)', ex8e_3(size))

Base matrix:
  64   2   3  61  60   6   7  57
   9  55  54  12  13  51  50  16
  17  47  46  20  21  43  42  24
  40  26  27  37  36  30  31  33
  32  34  35  29  28  38  39  25
  41  23  22  44  45  19  18  48
  49  15  14  52  53  11  10  56
   8  58  59   5   4  62  63   1
Result a)
  64   0   0  61  60   0   0  57
   0  55  54   0   0  51  50   0
   0  47  46   0   0  43  42   0
  40   0   0  37  36   0   0  33
  32  34  35   0   0  38  39   0
  41   0   0  44  45   0   0  48
  49   0   0  52  53   0   0  56
   0  58  59   0   0  62  63   0
Result b)
  64   2   3  61  60   6   7  57
   9  55  54  12  13  51  50  16
  17  47  46  20  21  43  42  24
  40  26  27  37  36  30  31  33
  41  23  22  44  45  19  18  48
  49  15  14  52  53  11  10  56
   8  58  59   5   4  62  63   1
Result c)
  64   2   3  61  60   6   7
   9  55  54  12  13  51  50
  17  47  46  20  21  43  42
  40  26  27  37  36  30  31
  32  34  35  29  28  38  39
  41  23  22  44  45  19  18
  49  15  14  52  53  11

# Exercise 9

In [54]:
from scipy import sparse 

np.random.seed(623827)
n = 8; d = 0.1
A = sparse.rand(n, n, d, format='csc'); print(A.todense())

### a ###
def ex9a(matrix):
    I, J, V = sparse.find(matrix)
    matrix[I, J] = 10*I + J

    return matrix.todense()

ex9a(A.copy())

### b ###

def ex9a():
    A[A == 0] = 2
    return A.todense()

### c ###
def ex9c(matrix):
    I, J, V = sparse.find(matrix)
    matrix[I, J] = J

    return matrix.todense()

ex9c(A.copy())

### d ###
# A.todense()

[[0.         0.         0.         0.         0.37189458 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.71963797 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.02584222 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.50721234 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.9507732  0.         0.         0.79845092 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]


matrix([[0., 0., 0., 0., 4., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 3., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 4., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

# Exercise 10

In [55]:
n = 7
np.random.seed(10)
suit, rank = np.random.randint(1, 14, size=n), np.random.randint(1, 5, size=n)

H = np.array(list(zip(suit,rank, np.arange(n))))
print("Hand:")
print(np.delete(H,2,axis=1))

H_sorted_on_rank = H[np.argsort(H[:,0])][::-1]
print("Hand sorted on rank with indices of original hand:")
print(H_sorted_on_rank)

H_highest_rank_per_suit = H_sorted_on_rank[np.unique(H_sorted_on_rank[:,1], return_index=True)[1]]
print("Highest rank per suit:")
print(H_highest_rank_per_suit)

sorted_answer = H_highest_rank_per_suit[np.argsort(H_highest_rank_per_suit[:,2])]
print('Sorted Highest rank per suit:')
print(sorted_answer)

print("Answer:")
print(np.delete(sorted_answer,2, axis=1))

Hand:
[[10  2]
 [ 5  1]
 [ 1  2]
 [ 2  2]
 [12  3]
 [13  1]
 [10  2]]
Hand sorted on rank with indices of original hand:
[[13  1  5]
 [12  3  4]
 [10  2  6]
 [10  2  0]
 [ 5  1  1]
 [ 2  2  3]
 [ 1  2  2]]
Highest rank per suit:
[[13  1  5]
 [10  2  6]
 [12  3  4]]
Sorted Highest rank per suit:
[[12  3  4]
 [13  1  5]
 [10  2  6]]
Answer:
[[12  3]
 [13  1]
 [10  2]]


# Exercise 11

In [57]:
n=4; m=5
A = np.random.randint(-10, 10, size=(n,m))

# Exercise 11a
isL = lambda x: np.all(x.diagonal() > 0) & np.all(x[~np.eye(x.shape[0], x.shape[1], dtype=np.bool)] <=0)
isL(A)

# Exercise 11b
A = sparse.csc_matrix([[1, 0, -2], [0, 4, 0], [-9, -2, 6]])
print(isL(A))

# Exercise 11c
A = sparse.csc_matrix([[-2, -6, 0, 1], [5, 11, -8, -9], [0, 20, 22, -4], [3, 2, 1, -7]])
print(isL(A))

True
False


# Exercise 12

In [ ]:
n=4; m=5
A = np.random.randint(-10, 10, size=(n,m))

# Exercise 11a
isL = lambda x: np.all(x.diagonal() > 0) & np.all(x[~np.eye(x.shape[0], x.shape[1], dtype=np.bool)] <=0)
isL(A)

# Exercise 11b
A = sparse.csc_matrix([[1, 0, -2], [0, 4, 0], [-9, -2, 6]])
print(isL(A))

# Exercise 11c
A = sparse.csc_matrix([[-2, -6, 0, 1], [5, 11, -8, -9], [0, 20, 22, -4], [3, 2, 1, -7]])
print(isL(A))

In [ ]:
instances = 100
n = 10000
t = timeit.Timer(functools.partial(f, n))
f_time = t.timeit(instances) / instances
print("Timing for f: {:.10f} sec.".format(f_time))
t = timeit.Timer(functools.partial(tridiag, n))
tridiag_time = t.timeit(instances) / instances
print("Timing for tridiag: {:.10f} sec.".format(tridiag_time))

print("tridiag is {:.1f} times faster than f".format(f_time / tridiag_time))